import { FormEvent, useState } from 'react';
import AdminPage from '@/Components/AdminPage';
import Button from '@/Components/ui/Button';
import DataTable, { type Column } from '@/Components/ui/DataTable';
import Dialog from '@/Components/ui/Dialog';
import { FormError, SelectField, TextAreaField, TextField } from '@/Components/ui/Form';
import Badge, { humanize } from '@/Components/ui/Badge';
import { Card, ErrorPanel, Skeleton } from '@/Components/ui/Page';
import ProductPicker from '@/Components/ProductPicker';
import { useAccess } from '@/lib/access';
import { useApi, usePagedApi } from '@/lib/useApi';
import { useForm } from '@/lib/useForm';
import { adminFetch } from '@/lib/adminApi';
import type { Brand, Category } from '@/lib/catalog';

/**
 * Module 16 SEO settings (/api/v1/seo-settings): the title, description,
 * canonical address, sharing (Open Graph) fields and robots choice, for
 * the whole store or for one product, category, brand or page.
 *
 * These are plain text and https addresses, validated by the server. No
 * custom HTML or script can be entered here: the backend has no such
 * field. Sitemap and robots.txt are generated by the storefront and have
 * no settings in the API, so none are shown.
 */
type SeoSetting = {
  id: number;
  seoable_type: string;
  seoable_id: number | null;
  title: string | null;
  meta_description: string | null;
  canonical_override: string | null;
  og_title: string | null;
  og_description: string | null;
  og_image_url: string | null;
  robots_index: string;
  robots_follow: string;
};

type Values = { title: string; meta_description: string; canonical_override: string; og_title: string; og_description: string; og_image_url: string; robots_index: string; robots_follow: string };
type Target = { type: string; id: number | null; name: string };

function valuesFrom(setting: SeoSetting | undefined): Values {
  return {
    title: setting?.title ?? '',
    meta_description: setting?.meta_description ?? '',
    canonical_override: setting?.canonical_override ?? '',
    og_title: setting?.og_title ?? '',
    og_description: setting?.og_description ?? '',
    og_image_url: setting?.og_image_url ?? '',
    robots_index: setting?.robots_index ?? 'index',
    robots_follow: setting?.robots_follow ?? 'follow',
  };
}

function SeoForm({ target, setting, canManage, onSaved, onCancel }: { target: Target; setting: SeoSetting | undefined; canManage: boolean; onSaved: () => void; onCancel?: () => void }) {
  const form = useForm<Values>(valuesFrom(setting));
  const { values, set } = form;

  async function save(event: FormEvent) {
    event.preventDefault();
    const empty = (text: string) => (text.trim() === '' ? null : text);
    const body = {
      seoable_type: target.type,
      seoable_id: target.id,
      title: empty(values.title),
      meta_description: empty(values.meta_description),
      canonical_override: empty(values.canonical_override),
      og_title: empty(values.og_title),
      og_description: empty(values.og_description),
      og_image_url: empty(values.og_image_url),
      robots_index: values.robots_index,
      robots_follow: values.robots_follow,
    };
    if ((await form.submit(() => adminFetch('/seo-settings', { method: 'POST', body }), 'SEO settings saved.')) !== undefined) onSaved();
  }

  return (
    <form onSubmit={save} className="space-y-4" noValidate>
      <FormError message={form.formError} />
      <TextField label="Search title" optional value={values.title} onChange={(v) => set('title', v)} error={form.errors.title} maxLength={255} hint="The headline in search results. Empty: the page's own name is used." />
      <TextAreaField label="Search description" optional rows={2} value={values.meta_description} onChange={(v) => set('meta_description', v)} error={form.errors.meta_description} maxLength={320} hint={`${values.meta_description.length} of 320 characters.`} />
      <TextField label="Canonical address" optional type="url" value={values.canonical_override} onChange={(v) => set('canonical_override', v)} error={form.errors.canonical_override} hint="Only when this content also lives at another address that should count as the original." />
      <div className="grid gap-4 sm:grid-cols-2">
        <TextField label="Title when shared" optional value={values.og_title} onChange={(v) => set('og_title', v)} error={form.errors.og_title} maxLength={255} />
        <TextField label="Image when shared" optional type="url" value={values.og_image_url} onChange={(v) => set('og_image_url', v)} error={form.errors.og_image_url} hint="A full web address of an image." />
      </div>
      <TextAreaField label="Description when shared" optional rows={2} value={values.og_description} onChange={(v) => set('og_description', v)} error={form.errors.og_description} maxLength={320} />
      <div className="grid gap-4 sm:grid-cols-2">
        <SelectField
          label="Search engines may list it"
          value={values.robots_index}
          onChange={(v) => set('robots_index', v)}
          error={form.errors.robots_index}
          options={[{ value: 'index', label: 'Yes (index)' }, { value: 'noindex', label: 'No (noindex)' }]}
          hint={target.type === 'store' && values.robots_index === 'noindex' ? 'Warning: this hides your whole store from search engines.' : undefined}
        />
        <SelectField label="Search engines may follow its links" value={values.robots_follow} onChange={(v) => set('robots_follow', v)} error={form.errors.robots_follow} options={[{ value: 'follow', label: 'Yes (follow)' }, { value: 'nofollow', label: 'No (nofollow)' }]} />
      </div>
      {canManage ? (
        <div className="flex justify-end gap-2">
          {onCancel && <Button onClick={onCancel} disabled={form.busy}>Cancel</Button>}
          <Button type="submit" variant="primary" busy={form.busy} busyLabel="Saving…">Save</Button>
        </div>
      ) : (
        <p className="text-sm text-slate-600">Your role can view these settings but not change them.</p>
      )}
    </form>
  );
}

function AddDialog({ onClose, onPicked }: { onClose: () => void; onPicked: (target: Target) => void }) {
  const [type, setType] = useState('product');
  const categories = useApi<{ data: Category[] }>(type === 'category' ? '/categories' : null);
  const brands = useApi<{ data: Brand[] }>(type === 'brand' ? '/brands' : null);
  const pages = usePagedApi<{ id: number; title: string }>(type === 'content_page' ? '/content-pages' : null);
  const [chosen, setChosen] = useState('');

  const choices: { id: number; name: string }[] =
    type === 'category' ? (categories.data?.data ?? []) : type === 'brand' ? (brands.data?.data ?? []) : type === 'content_page' ? (pages.rows ?? []).map((row) => ({ id: row.id, name: row.title })) : [];

  return (
    <Dialog open title="SEO for one page" description="Choose what the settings are for." onClose={onClose}>
      <div className="space-y-4">
        <SelectField
          label="Kind"
          value={type}
          onChange={(value) => { setType(value); setChosen(''); }}
          options={[{ value: 'product', label: 'Product' }, { value: 'category', label: 'Category' }, { value: 'brand', label: 'Brand' }, { value: 'content_page', label: 'Content page' }]}
        />
        {type === 'product' ? (
          <ProductPicker onPick={({ product }) => onPicked({ type: 'product', id: product.internal_id, name: product.name })} />
        ) : (
          <>
            <SelectField label={humanize(type)} value={chosen} onChange={setChosen} placeholder="Choose…" options={choices.map((choice) => ({ value: String(choice.id), label: choice.name }))} />
            <div className="flex justify-end gap-2">
              <Button onClick={onClose}>Cancel</Button>
              <Button variant="primary" disabled={chosen === ''} onClick={() => onPicked({ type, id: Number(chosen), name: choices.find((choice) => String(choice.id) === chosen)?.name ?? '' })}>Continue</Button>
            </div>
          </>
        )}
      </div>
    </Dialog>
  );
}

export default function Seo() {
  const access = useAccess();
  const canManage = access.can('seo.manage');
  const state = useApi<{ data: SeoSetting[] }>('/seo-settings');
  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState<Target | null>(null);

  const settings = state.data?.data ?? null;
  const storeSetting = settings?.find((setting) => setting.seoable_type === 'store');
  const others = settings?.filter((setting) => setting.seoable_type !== 'store') ?? null;
  const settingFor = (target: Target) => settings?.find((setting) => setting.seoable_type === target.type && setting.seoable_id === target.id);

  const columns: Column<SeoSetting>[] = [
    { key: 'for', header: 'For', render: (setting) => <span className="font-medium">{humanize(setting.seoable_type)} #{setting.seoable_id}</span> },
    { key: 'title', header: 'Search title', priority: true, render: (setting) => setting.title ?? '—' },
    { key: 'robots', header: 'Listed', render: (setting) => <Badge tone={setting.robots_index === 'index' ? 'green' : 'amber'}>{setting.robots_index === 'index' ? 'Yes' : 'Hidden from search'}</Badge> },
    {
      key: 'actions', header: 'Actions', srOnlyHeader: true, align: 'right', priority: true,
      render: (setting) => (
        <Button size="sm" variant="ghost" onClick={() => setEditing({ type: setting.seoable_type, id: setting.seoable_id, name: `${humanize(setting.seoable_type)} #${setting.seoable_id}` })}>
          {canManage ? 'Edit' : 'View'}
        </Button>
      ),
    },
  ];

  return (
    <AdminPage title="SEO" description="How your store appears in search engines and when links are shared.">
      {state.error ? (
        <ErrorPanel message={state.error} onRetry={state.reload} />
      ) : settings === null ? (
        <Skeleton lines={5} />
      ) : (
        <div className="space-y-4">
          <Card title="Whole store" description="Used for your home page and wherever a page has no settings of its own.">
            <SeoForm key={storeSetting?.id ?? 'new'} target={{ type: 'store', id: null, name: 'Whole store' }} setting={storeSetting} canManage={canManage} onSaved={state.reload} />
          </Card>

          <Card title="Individual pages" description="Settings for one product, category, brand or content page." actions={canManage && <Button size="sm" onClick={() => setAdding(true)}>Add settings for a page</Button>}>
            <DataTable caption="SEO settings of individual pages" columns={columns} rows={others} rowKey={(setting) => setting.id} empty={<p className="text-sm text-slate-600">No page has its own settings. They all use the store's.</p>} />
          </Card>
        </div>
      )}

      {adding && <AddDialog onClose={() => setAdding(false)} onPicked={(target) => { setAdding(false); setEditing(target); }} />}
      {editing && (
        <Dialog open wide title={`SEO: ${editing.name}`} onClose={() => setEditing(null)}>
          <SeoForm
            target={editing}
            setting={settingFor(editing)}
            canManage={canManage}
            onCancel={() => setEditing(null)}
            onSaved={() => {
              setEditing(null);
              state.reload();
            }}
          />
        </Dialog>
      )}
    </AdminPage>
  );
}
